# Generated by Django 5.1.3 on 2024-11-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer_app', '0005_alter_userprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
